CREATE TABLE Banished(
DemonName NVARCHAR(30),
EID INT,
[DateTime] DATETIME CHECK([DateTime] <= GETDATE() AND [DateTime] >= '1900-1-1 00:00:00.000') NOT NULL
PRIMARY KEY(DemonName,EID)
FOREIGN KEY(DemonName) REFERENCES Demon(Name),
FOREIGN KEY(EID) REFERENCES Exorcist(ID)
)