CREATE TABLE Rating(
EID INT,
CID INT,
Stars INT CHECK(Stars <=5 AND Stars>=0) NOT NULL,
Comment NVARCHAR(100)
PRIMARY KEY(EID,CID),
FOREIGN KEY(EID) REFERENCES Exorcist(ID),
FOREIGN KEY(CID) REFERENCES Customer(ID)
)